### ISSUE TITLE
Update to Instagram v63.0

### ISSUE THREAD

**Issue by potatoeux** [JMccormick264/InstagramPP#10]
title

**Comment by gcseed** [comment]
We need the update for sure, the layout on the XS Max is completely messed up with the V55. 
Thank you very much if anyone can keep the updates going!

**Comment by JMccormick264** [comment]
Unlim released a tweak update that supports v67 on sideload. I am waiting on a regram and repost bug to be fixed for sideload. He fixed it on JB today. Once that is updated I will update the tweak and the app to the latest versions of both.

**Comment by gcseed** [comment]
> Unlim released a tweak update that supports v67 on sideload. I am waiting on a regram and repost bug to be fixed for sideload. He fixed it on JB today. Once that is updated I will update the tweak and the app to the latest versions of both.

Thank you very much! You guys are the best!

**Comment by JMccormick264** [comment]
Went ahead and pushed the IPA. ReGram and Repost still need fixing. Once those are fixed I will upload at this time, App version 68.0, and the latest tweak.

**Comment by potatoeux** [comment]
Thanks!

**Comment by JMccormick264** [comment]
Been updated to the latest sideload and app store version
Repost and ReGram bug has been fixed as of 1.8r-195
