### ISSUE TITLE
latest version (v12.0_1.8r-73) crash issue (i6 10.3.1)

### ISSUE THREAD

**Issue by thekio1984** [JMccormick264/InstagramPP#2]
was working fine, then for no reason kept crashing, 7day impactor signing not even 3days into, iphone kept freezing & crashing back to home screen, even after revoke certs & reinstall, it still did it, dunno if its the app or my phone, but was fine on the previous version...got it working again after a few tries, dunno if itll do it again though..but good work none the less..kudos 👍 & keep them updates coming 💯

**Comment by JMccormick264** [comment]
let me try on my end. I am not the developer though

**Comment by thekio1984** [comment]
nice on the quick reply.. tbh ive used here since i lost my jb, every update has been fine, ive only used it since like monday, just a lil random, its quite possibly my phone, just a bit strange how it did it mid usage yet has been fine, at 1st i thought was cert expired, as it was a crash like that, if you know what i mean, then my iphone went glitchy & froze, it messed with the digitiser/screen touch..even after hard reset..idk though, just thought id say in case others have the issue... :)

**Comment by JMccormick264** [comment]
https://github.com/JMccormick264/InstagramPP/releases/tag/Re-Release @thekio1984 Try 11.0

**Comment by ace101boss** [comment]
@JMccormick264 I can confirm that v12.0_1.8r-73 is crashing on iOS 10.3.3 on iPhone 6s Plus. It doesnt happen immediately though, it will start to happen once you minimize or use a Instagram ++ feature and then minimize the app. 11.0 seems resolve the issue of the crashing - Ill continue to test and report.

**Comment by thekio1984** [comment]
same as @ace101boss said....will try 11 out :) cheers xD

**Comment by thekio1984** [comment]
11.0 works like a charm..no issues at all :) thanks again :D
